-- =============================================================================
-- Supabase Schema for Secure File Management System
-- =============================================================================
-- Copy and run this script in the Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql
-- =============================================================================

-- 1. Create tables
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    totp_secret TEXT,
    two_factor_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename TEXT NOT NULL,
    original_name TEXT NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    file_size BIGINT NOT NULL DEFAULT 0,
    file_type TEXT,
    is_encrypted BOOLEAN DEFAULT TRUE,
    storage_path TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.file_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES public.files(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    permission TEXT NOT NULL DEFAULT 'read' CHECK (permission IN ('read', 'write')),
    granted_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE (file_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    resource TEXT,
    details TEXT,
    ip_address TEXT,
    timestamp TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.share_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES public.files(id) ON DELETE CASCADE,
    sender_user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    target_user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    permission TEXT,
    previous_permission TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Indexes for high performance
CREATE INDEX IF NOT EXISTS idx_users_username_lower ON public.users (LOWER(username));
CREATE INDEX IF NOT EXISTS idx_files_owner_id ON public.files (owner_id);
CREATE INDEX IF NOT EXISTS idx_files_created_at ON public.files (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_file_permissions_user_id ON public.file_permissions (user_id);
CREATE INDEX IF NOT EXISTS idx_file_permissions_file_id ON public.file_permissions (file_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON public.audit_log (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON public.audit_log (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_share_history_sender ON public.share_history (sender_user_id);
CREATE INDEX IF NOT EXISTS idx_share_history_created_at ON public.share_history (created_at DESC);

-- 3. Automatic updated_at trigger function
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at triggers
DROP TRIGGER IF EXISTS set_users_updated_at ON public.users;
CREATE TRIGGER set_users_updated_at
    BEFORE UPDATE ON public.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_files_updated_at ON public.files;
CREATE TRIGGER set_files_updated_at
    BEFORE UPDATE ON public.files
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_file_permissions_updated_at ON public.file_permissions;
CREATE TRIGGER set_file_permissions_updated_at
    BEFORE UPDATE ON public.file_permissions
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- 4. Enable Row Level Security (RLS)
-- By default, backend with service_role key bypasses RLS, but these keep it secure.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.file_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.share_history ENABLE ROW LEVEL SECURITY;

-- Allow service_role or backend full access
CREATE POLICY "Allow backend service access on users" ON public.users FOR ALL USING (true);
CREATE POLICY "Allow backend service access on files" ON public.files FOR ALL USING (true);
CREATE POLICY "Allow backend service access on file_permissions" ON public.file_permissions FOR ALL USING (true);
CREATE POLICY "Allow backend service access on audit_log" ON public.audit_log FOR ALL USING (true);
CREATE POLICY "Allow backend service access on share_history" ON public.share_history FOR ALL USING (true);

-- 5. Supabase Storage Setup (Optional Cloud Storage)
-- Create the 'secure-files' storage bucket if storage extension is active
INSERT INTO storage.buckets (id, name, public)
VALUES ('secure-files', 'secure-files', false)
ON CONFLICT (id) DO NOTHING;
